name: Build Plugin

on:
  push:
    branches: [ "v5" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 'Install dependencies'
        run: npm install

      - name: Build plugin
        run: npm run build

      - name: Unzip artifact for clean upload
        run: |
          mkdir -p release
          unzip mspring-theme.zip -d release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mspring-theme
          path: release/
